export const categoryList = [
  {
    id: 1,
    value: "paint",
    label: " painting ",
  },
  {
    id: 2,
    value: "craft",
    label: "hand crafts",
  },
  {
    id: 3,
    value: "sewing",
    label: "  sewing  ",
  },
  {
    id: 4,
    value: "wood",
    label: " wood craft",
  },
];

export const ratingList = [
  {
    id: 1,
    value: "1",
    label: "buy",
  },
  {
    id: 2,
    value: "2",
    label: "buy",
  },
  {
    id: 3,
    value: "3",
    label: "buy",
  },
  {
    id: 4,
    value: "4",
    label: "4🌟",
  },
  {
    id: 5,
    value: "5",
    label: "5🌟",
  },
];

export const dataList = [
  {
    id: 1,
    title: "bottle house",
    serviceTime: "45-60min",
    deliveryFee: 3.44,
    category: "paint",
    category1: "time",
    location: "trichy",
    rating: 5,
    price: 250,
    coverSrc: "/images/craft/1.jpg",
  },
  {
    id: 2,
    title: "lamp",
    serviceTime: "15-20min",
    deliveryFee: 4.94,
    category1: "time",

    category: "paint",
    location: "madurai",
    rating: 4,
    price: 200,
    coverSrc: "/images/craft/2.jpg",
  },
  {
    id: 3,
    title: "pillow",
    serviceTime: "30-22min",
    deliveryFee: 4.94,
    category1: "time",

    category: "sewing",
    location: "karaikudi",
    rating: 3,
    price: 300,
    coverSrc: "/images/craft/13.jpg",
  },
  {
    id: 4,
    title: "harmer",
    serviceTime: "10-18min",
    deliveryFee: 2.14,
    category: "wood",
    category1: "time",

    location: "trichy",
    rating: 1,
    price: 1000,
    coverSrc: "/images/craft/16.jpg",
  },
  {
    id: 5,
    title: "water paint",
    serviceTime: "25-30min",
    deliveryFee: 6.79,
    category1: "time",

    category: "paint",
    location: "madurai",
    rating: 5,
    price: 700,
    coverSrc: "/images/craft/3.jpg",
  },
  {
    id: 6,
    title: "pot",
    serviceTime: "5-15min",
    deliveryFee: 2.87,
    category: "craft",
    category1: "time",

    location: "karaikudi",
    rating: 5,
    price: 690,
    coverSrc: "/images/craft/8.jpg",
  },
  {
    id: 7,
    title: "mirror arch",
    serviceTime: "50-65min",
    deliveryFee: 8.5,
    category: "craft",
    location: "trichy",
    category1: "time",

    rating: 2,
    price: 120,
    coverSrc: "/images/craft/6.jpg",
  },
  {
    id: 8,
    title: "castle",
    serviceTime: "10-15min",
    deliveryFee: 1.8,
    category: "paint",
    location: "madurai",
    category1: "time",

    rating: 1,
    price: 140,
    coverSrc: "/images/craft/4.jpg",
  },
  {
    id: 9,
    title: "peacock earing",
    serviceTime: "12-18min",
    deliveryFee: 3.33,
    category: "craft",
    category1: "time",

    location: "karaikudi",
    rating: 4,
    price: 100,
    coverSrc: "/images/craft/7.jpg",
  },
  {
    id: 10,
    title: "batch",
    serviceTime: "30-38min",
    deliveryFee: 1.9,
    category: "sewing",
    category1: "time",

    location: "trichy",
    rating: 2,
    price: 110,
    coverSrc: "/images/craft/14.jpg",
  },
  {
    id: 11,
    title: "toy stand",
    serviceTime: "16-20min",
    deliveryFee: 4.1,
    category: "wood",
    location: "madurai",
    category1: "time",

    rating: 3,
    price: 720,
    coverSrc: "/images/craft/18.jpg",
  },
  {
    id: 12,
    title: "toy",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "craft",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 160,
    coverSrc: "/images/craft/9.jpg",
  },
  {
    id: 13,
    title: "mirror stand",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "wood",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 2000,
    coverSrc: "/images/craft/19.jpg",
  },
  {
    id: 14,
    title: "bulb arch",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "craft",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 200,
    coverSrc: "/images/craft/10.jpg",
  },
  {
    id: 15,
    title: "taj mahal",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "paint",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 300,
    coverSrc: "/images/craft/5.jpg",
  },
  {
    id: 16,
    title: "hand bag",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "sewing",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 400,
    coverSrc: "/images/craft/11.jpg",
  },
  {
    id: 17,
    title: "wood arch",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "wood",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 420,
    coverSrc: "/images/craft/17.jpg",
  },
  {
    id: 18,
    title: "pen stand",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "sewing",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 110,
    coverSrc: "/images/craft/12.jpg",
  },
  {
    id: 19,
    title: "cloth arch",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "sewing",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 100,
    coverSrc: "/images/craft/15.jpg",
  },
  {
    id: 20,
    title: "paper roll",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "wood",
    category1: "time",

    location: "karaikudi",
    rating: 2,
    price: 900,
    coverSrc: "/images/craft/20.jpg",
  },
];
